#!/usr/bin/env bash
# load the environment to work with drush and drupal containers
# do not run this script but source it like
# . load-env
#
. docker/environment > /dev/null
. docker/functions

if [ -e ".console/console.rc" ]; then
    . .console/console.rc 2>/dev/null
fi

if [ -f ".drush/drush.bashrc" ] ; then
  . .drush/drush.bashrc
fi

# Include Drush completion.
if [ -f ".drush/drush.complete.sh" ] ; then
  . .drush/drush.complete.sh
fi

## Include Drush prompt customizations.
#if [ -f ".drush/drush.prompt.sh" ] ; then
#  . .drush/drush.prompt.sh
#fi

echo "use \"drush\" and \"drupal\" to call dockerized Drush and Drupal console in Project ${PROJECT_NAME} ($(projectdir))"