#!/usr/bin/env bash

# Define useful aliases and functions and prepare the directory structure.
# This script can be sourced from the project dir or from the docker dir inside the project dir.
# Other directories lead to unpredictable results!

pushd "$(pwd)" > /dev/null
if [ $(basename "$(pwd)") != "docker" ]; then
  cd docker
fi

# Load the environment
. environment > /dev/null

# set some variables
projectdir=$(dirname "$(pwd)")
net="${PROJECT_NAME}_dev_net"

appdir="${projectdir}/www"
consolevol="${projectdir}/.console:/root/.console"
drushvol="${projectdir}/.drush:/root/.drush"
node_version="my/node:latest"


popd >/dev/null

# @function relpath
#           determines the relative directory path name of a directory according to a given basedir
# @param basedir (default: $appdir)
# @param relativedir (default: current dir)
function relpath ()
{
    if [ "${1}" ] ; then
        basedir="${1}"
    else
        basedir="${appdir}"
    fi
    if [ "${2}" ]; then
        relativedir="${2}"
    else
        relativedir="$(pwd)"
    fi
    tail=$(basename "${relativedir}")
    root=$(dirname "${relativedir}")
    base="${basedir}"
    while [ "${root}" != "/" ] && [ "${root}" != "." ] && [ "${root}" != "${base}" ] ; do
        tailnew=$(basename ${root})/${tail}
        tail=${tailnew}
        rootnew=$(dirname ${root})
        root=${rootnew}
    done
    if [ ${root} != "/" ] && [ "${root}" != "." ] ; then
        echo ${tail}
    else
        echo docroot
    fi
}

# @function projectdir
#           returns the path of the project dir
function projectdir ()
{
    echo "${projectdir}"
}

# @function drush
#           calls dockerized drush for the current project. It uses the current directory as
#           working directory.
# @usage    drush drush commands...
function drush()
{
    docker run \
        --interactive \
        --rm \
        --volume="${appdir}":/app \
        --volume="${projectdir}/.drush:/root/.drush" \
        --workdir="/app/$(relpath)" \
        --net="${net}" \
        \
        my/drush "${@}"
}

# @function drupal
#           calls docerized drupal console for the current project. It uses the current directory as
#           working directory.
# @usage    drupal drupal-console commands...
function drupal()
{
    docker run \
        --interactive \
        --tty \
        --rm \
        --volume="${appdir}":/app \
        --volume="${projectdir}/.console:/root/.console" \
        --workdir="/app/$(relpath)" \
        --net="${net}" \
        \
        my/drupalconsole "${@}"
}

function node()
{
    docker run \
        --interactive \
        --tty \
        --rm \
        --volume="$(pwd)":/usr/src/app \
        --workdir=/usr/src/app \
        ${node_version} \
        \
        node "${@}"
}

function npm()
{
        docker run \
        --interactive \
        --tty \
        --rm \
        --volume="$(pwd)":/usr/src/app \
        --workdir=/usr/src/app \
        ${node_version} \
        \
        npm "${@}"
}

function gulp()
{
        docker run \
        --interactive \
        --tty \
        --rm \
        --volume="$(pwd)":/usr/src/app \
        --workdir=/usr/src/app \
        ${node_version} \
        \
        gulp "${@}"
}

# set aliases to invoke some tools in a container
alias drush=drush # drush.complete.sh requires an alias, does not act on functions
alias drupal=drupal # if scripts require an alias
alias node=node # if scripts require an alias
alias npm=npm # if scripts require an alias
alias gulp=gulp # if scripts require an alias

# prepare the directories to set ownership and access rights and to avoid scripts complaining about missing folders
old_umask=$(umask)
umask 000
mkdir "${projectdir}/.drush" 2> /dev/null
mkdir "${projectdir}/.log" 2> /dev/null
mkdir "${projectdir}/.mysql" 2> /dev/null
mkdir "${projectdir}/.sendmail" 2> /dev/null
mkdir "${projectdir}/www" 2> /dev/null
mkdir "${projectdir}/www/docroot" 2> /dev/null # The document root of the webserver
mkdir "${projectdir}/www/tmp" 2> /dev/null # To be used by temporary files in Drupal
mkdir "${projectdir}/www/config" 2> /dev/null # Config files for Drupal 8 (not accessible by the browser!)
mkdir "${projectdir}/www/config/default" 2> /dev/null # similar to the sites structure
mkdir "${projectdir}/www/config/default/sync" 2> /dev/null
mkdir "${projectdir}/www/private" 2> /dev/null # private files go here (not accessible by the browser!)
mkdir "${projectdir}/www/private/default" 2> /dev/null # similar to the sites structure
mkdir "${projectdir}/www/private/default/files" 2> /dev/null
mkdir "${projectdir}/www/private/default/files/backup_migrate" 2> /dev/null # it can't do it itself ?!
umask "${old_umask}"
